# Importation de `torch`

In [2]:
import torch, torchvision
import numpy as np

# Tenseurs

## Initialisation de tenseurs

### À partir de zéros et de uns ###

In [3]:
t = torch.zeros(2, 2)
x = torch.ones(2, 2, dtype=torch.int)
print(t)
print(t.dtype)
print(x)


tensor([[0., 0.],
        [0., 0.]])
torch.float32
tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


Par défaut `torch` spécifie le type de donnée par `float32`. On peut changer le type de donnée avec `dtype=...`

### Aléatoirement ###

In [4]:
torch.manual_seed(2021)
t = torch.rand(2, 2)
x = torch.rand(2, 2)

torch.manual_seed(2021)
y = torch.rand(2, 2)

print(t)
print(x)
print(y)

tensor([[0.1304, 0.5134],
        [0.7426, 0.7159]])
tensor([[0.5705, 0.1653],
        [0.0443, 0.9628]])
tensor([[0.1304, 0.5134],
        [0.7426, 0.7159]])


On peut utiliser une `seed` pour retrouver le même tenseur générer aléatoirement

### À partir de données ###

In [5]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

### À partir de `numpy` ###


In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

### À partir d'un autre tenseur ### 

In [7]:
x_ones = torch.ones_like(x_data) # même propriétés que x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # redéfinit datatype de x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5705, 0.1653],
        [0.0443, 0.9628]]) 



## Les propriétés des tenseurs ##

In [8]:
tensor = torch.rand(3,4)

print(f"Forme : {tensor.shape}")
print(f"Datatype : {tensor.dtype}")
print(f"Stockage : {tensor.device}")

Forme : torch.Size([3, 4])
Datatype : torch.float32
Stockage : cpu


## Opérations sur des tenseurs ##

### Opération basique

In [9]:
r = torch.rand(2, 2) - 0.5 * 2 # values between -1 and 1
print('A random matrix, r:')
print(r)

# Common mathematical operations are supported:
print('\nAbsolute value of r:')
print(torch.abs(r))

# ...as are trigonometric functions:
print('\nInverse sine of r:')
print(torch.asin(r))

# ...and linear algebra operations like determinant and singular value decomposition
print('\nDeterminant of r:')
print(torch.det(r))
print('\nSingular value decomposition of r:')
print(torch.svd(r))

# ...and statistical and aggregate operations:
print('\nAverage and standard deviation of r:')
print(torch.std_mean(r))
print('\nMaximum value of r:')
print(torch.max(r))

A random matrix, r:
tensor([[-0.1950, -0.6964],
        [-0.0058, -0.4975]])

Absolute value of r:
tensor([[0.1950, 0.6964],
        [0.0058, 0.4975]])

Inverse sine of r:
tensor([[-0.1963, -0.7703],
        [-0.0058, -0.5208]])

Determinant of r:
tensor(0.0930)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[ 0.8271,  0.5620],
        [ 0.5620, -0.8271]]),
S=tensor([0.8713, 0.1068]),
V=tensor([[-0.1889, -0.9820],
        [-0.9820,  0.1889]]))

Average and standard deviation of r:
(tensor(0.3078), tensor(-0.3487))

Maximum value of r:
tensor(-0.0058)


### Standard numpy-like indexing and slicing:

In [10]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Concaténation

In [11]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### Multiplication

In [12]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [13]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


**In-place operations**
Operations that have a ``_`` suffix are in-place. For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.

In [14]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


Si on modifie un tenseur stocké sur le cpu, la même matrice `numpy` sera changée car elle est également stokée sur le cpu et vice-versa.

In [15]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")


t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


# Autograd

## Exemple de RNN (recurent neural network)

In [16]:
x = torch.randn(1, 10, requires_grad=True) #tenseur d'entrée
prev_h = torch.randn(1 ,20) #couche cachée
w_h = torch.randn(20 ,20) #poids de la couche cachée
w_x = torch.randn(20 ,10) #poids du tenseur d'entrée

i2h = torch.mm(w_x, x.t()) #multiplication de x et w_x (mm : matrix multiplication)
h2h = torch.mm(w_h, prev_h.t())

next_h = i2h + h2h #somme des multiplications
next_h = next_h.tanh() #fonction d'activitaion 

loss = next_h.sum() #fonction à optimiser
loss.backward() #calcul les gradients pour la fonction loss

## Exemple d'étape d'entrainement

In [17]:
model = torchvision.models.resnet18(pretrained=True) #model préentrainé
data = torch.rand(1, 3, 64, 64) # tenseur aléatoire représentant une image 3D de résolution 64x64
labels = torch.rand(1, 1000)

prediction = model(data) #passe avant, on entre les données dans le modèle afin d'obtenir ses prédictions

loss = (prediction - labels).sum()
loss.backward() # passe arrière

optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

optim.step() #gradient descent

## Exemple de calcul du gradient avec autograd

In [18]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

`requires_grad=True` implique que toutes les opérations appliquées sur le tenseur seront suivies par autograd

In [19]:
Q = 3*a**3 - b**2 

external_grad = torch.tensor([1., 1.]) #le gradient de Q selon lui même est égale à 1
Q.backward(gradient=external_grad)

Comme `Q` est un vecteur, on doit spécifier le gradient lorsqu'on utilise `.backward()`

In [20]:
# check if collected gradients are correct
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


Comme l'égalité est respectée entre les dérivées partielles de `Q` et `a.grad()` ou `b.grad()` on a la preuve que autograd a bien fonctionné.

## Exemple de NN

In [21]:
import torch.nn as nn
import torch.nn.functional as F

### Définition du réseaux

In [22]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)  # 5*5 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square, you can specify with a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = torch.flatten(x, 1) # flatten all dimensions except the batch dimension
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


### Passe avant (forward pass) et arrière (backward pass)

In [23]:
params = list(net.parameters())
print(len(params))
print(params[0].size())  # conv1's .weight

input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

net.zero_grad()
out.backward(torch.randn(1, 10))

10
torch.Size([6, 1, 5, 5])
tensor([[-0.0235,  0.0806,  0.0334,  0.0452, -0.0450, -0.0410,  0.0937,  0.1087,
         -0.1257,  0.0126]], grad_fn=<AddmmBackward>)


### Fonction objectif (loss function) - Erreur moyenne carrée

In [34]:
output = net(input)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss() # mean square error

loss = criterion(output, target)
print(loss)

tensor(1.0728, grad_fn=<MseLossBackward>)


## Backprop

In [36]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([-0.0255,  0.0324,  0.0317,  0.0303, -0.0104, -0.0232])


## Update the weights

In [37]:
learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)

import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()    # Does the update